name: Update posts in submodule

on:
  repository_dispatch:
    types: [posts-push]
  workflow_dispatch:

jobs:
  sync:
    name: Sync submodule
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # token: ${{ secrets.AUTO_SYNC_POSTS_PAT }}
        ssh-key: ${{ secrets.BLOG_REPO_DEPLOY_PRIVATE_KEY }}
        submodules: true
        lfs: true

    # Update references
    - name: Git Sumbodule Update
      run: |
        git pull --recurse-submodules
        git submodule update --remote --recursive

    - name: Commit update
      run: |
        git config --global user.name 'Git bot'
        git config --global user.email 'bot@noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"